.TH "C:/xampp/htdocs/framework Directory Reference" 3 "Sun May 10 2015" "Version 1.0" "frameworkandreu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/framework Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconstants\&.php\fP"
.br
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.in -1c
